<a href="https://www.kaggle.com/code/ramezmaged/heart-disease-risk-prediction?scriptVersionId=142671147" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

#Visual Libraries
import matplotlib.pyplot as plt
import seaborn as sns

# Importing necessary libraries for encoding
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder

# Importing necessary library for scaling
from sklearn.preprocessing import StandardScaler

# Importing necessary library for train-test split
from sklearn.model_selection import train_test_split

# Importing necessary libraries for model development and evaluation
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, roc_curve

# Importing necessary library for hyperparameter tuning
from sklearn.model_selection import RandomizedSearchCV

In [2]:
data = pd.read_csv("/kaggle/input/cardiovascular-diseases-risk-prediction-dataset/CVD_cleaned.csv")

In [3]:
data.head()

General_Health                  Checkup Exercise Heart_Disease Skin_Cancer  \
0           Poor  Within the past 2 years       No            No          No   
1      Very Good     Within the past year       No           Yes          No   
2      Very Good     Within the past year      Yes            No          No   
3           Poor     Within the past year      Yes           Yes          No   
4           Good     Within the past year       No            No          No   

  Other_Cancer Depression Diabetes Arthritis     Sex Age_Category  \
0           No         No       No       Yes  Female        70-74   
1           No         No      Yes        No  Female        70-74   
2           No         No      Yes        No  Female        60-64   
3           No         No      Yes        No    Male        75-79   
4           No         No       No        No    Male          80+   

   Height_(cm)  Weight_(kg)    BMI Smoking_History  Alcohol_Consumption  \
0        150.0        32.66  14.54             Yes                  0.0   
1        165.0        77.11  28.29              No                  0.0   
2        163.0        88.45  33.47              No                  4.0   
3        180.0        93.44  28.73              No                  0.0   
4        191.0        88.45  24.37             Yes                  0.0   

   Fruit_Consumption  Green_Vegetables_Consumption  FriedPotato_Consumption  
0               30.0                          16.0                     12.0  
1               30.0                           0.0                      4.0  
2               12.0                           3.0                     16.0  
3               30.0                          30.0                      8.0  
4                8.0                           4.0                      0.0

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 308854 entries, 0 to 308853
Data columns (total 19 columns):
 #   Column                        Non-Null Count   Dtype  
---  ------                        --------------   -----  
 0   General_Health                308854 non-null  object 
 1   Checkup                       308854 non-null  object 
 2   Exercise                      308854 non-null  object 
 3   Heart_Disease                 308854 non-null  object 
 4   Skin_Cancer                   308854 non-null  object 
 5   Other_Cancer                  308854 non-null  object 
 6   Depression                    308854 non-null  object 
 7   Diabetes                      308854 non-null  object 
 8   Arthritis                     308854 non-null  object 
 9   Sex                           308854 non-null  object 
 10  Age_Category                  308854 non-null  object 
 11  Height_(cm)                   308854 non-null  float64
 12  Weight_(kg)                   308854 non-nul

In [5]:
data.isnull().sum()

General_Health                  0
Checkup                         0
Exercise                        0
Heart_Disease                   0
Skin_Cancer                     0
Other_Cancer                    0
Depression                      0
Diabetes                        0
Arthritis                       0
Sex                             0
Age_Category                    0
Height_(cm)                     0
Weight_(kg)                     0
BMI                             0
Smoking_History                 0
Alcohol_Consumption             0
Fruit_Consumption               0
Green_Vegetables_Consumption    0
FriedPotato_Consumption         0
dtype: int64

In [6]:
data.describe()

Height_(cm)    Weight_(kg)            BMI  Alcohol_Consumption  \
count  308854.000000  308854.000000  308854.000000        308854.000000   
mean      170.615249      83.588655      28.626211             5.096366   
std        10.658026      21.343210       6.522323             8.199763   
min        91.000000      24.950000      12.020000             0.000000   
25%       163.000000      68.040000      24.210000             0.000000   
50%       170.000000      81.650000      27.440000             1.000000   
75%       178.000000      95.250000      31.850000             6.000000   
max       241.000000     293.020000      99.330000            30.000000   

       Fruit_Consumption  Green_Vegetables_Consumption  \
count      308854.000000                 308854.000000   
mean           29.835200                     15.110441   
std            24.875735                     14.926238   
min             0.000000                      0.000000   
25%            12.000000                      4.000000   
50%            30.000000                     12.000000   
75%            30.000000                     20.000000   
max           120.000000                    128.000000   

       FriedPotato_Consumption  
count            308854.000000  
mean                  6.296616  
std                   8.582954  
min                   0.000000  
25%                   2.000000  
50%                   4.000000  
75%                   8.000000  
max                 128.000000

In [7]:
cols = ['General_Health','Exercise','Heart_Disease','Skin_Cancer','Other_Cancer','Depression','Diabetes','Arthritis','Sex','Age_Category','Smoking_History']

In [8]:
for i in cols:
    print(data[i].value_counts())
    print()

General_Health
Very Good    110395
Good          95364
Excellent     55954
Fair          35810
Poor          11331
Name: count, dtype: int64

Exercise
Yes    239381
No      69473
Name: count, dtype: int64

Heart_Disease
No     283883
Yes     24971
Name: count, dtype: int64

Skin_Cancer
No     278860
Yes     29994
Name: count, dtype: int64

Other_Cancer
No     278976
Yes     29878
Name: count, dtype: int64

Depression
No     246953
Yes     61901
Name: count, dtype: int64

Diabetes
No                                            259141
Yes                                            40171
No, pre-diabetes or borderline diabetes         6896
Yes, but female told only during pregnancy      2646
Name: count, dtype: int64

Arthritis
No     207783
Yes    101071
Name: count, dtype: int64

Sex
Female    160196
Male      148658
Name: count, dtype: int64

Age_Category
65-69    33434
60-64    32418
70-74    31103
55-59    28054
50-54    25097
80+      22271
40-44    21595
45-49    20968
75-79    2070

In [9]:
cols_tmp = ['Exercise','Heart_Disease','Skin_Cancer','Other_Cancer','Depression','Arthritis','Smoking_History']

In [10]:
data[cols_tmp] = data[cols_tmp].replace({
    'Yes':1,
    'No':0
})

data[cols_tmp]

Exercise  Heart_Disease  Skin_Cancer  Other_Cancer  Depression  \
0              0              0            0             0           0   
1              0              1            0             0           0   
2              1              0            0             0           0   
3              1              1            0             0           0   
4              0              0            0             0           0   
...          ...            ...          ...           ...         ...   
308849         1              0            0             0           0   
308850         1              0            0             0           0   
308851         1              0            0             0           1   
308852         1              0            0             0           0   
308853         1              0            0             0           0   

        Arthritis  Smoking_History  
0               1                1  
1               0                0  
2               0                0  
3               0                0  
4               0                1  
...           ...              ...  
308849          0                0  
308850          0                0  
308851          0                1  
308852          0                0  
308853          0                0  

[308854 rows x 7 columns]

In [11]:
data['General_Health'].value_counts()

General_Health
Very Good    110395
Good          95364
Excellent     55954
Fair          35810
Poor          11331
Name: count, dtype: int64

In [12]:
data['General_Health'] = data['General_Health'].replace({
    'Very Good':5,
    'Good':4,
    'Excellent':3,
    'Fair':2,
    'Poor':1
})

In [13]:
data['General_Health'].value_counts()


General_Health
5    110395
4     95364
3     55954
2     35810
1     11331
Name: count, dtype: int64

In [14]:
data['Sex'] = data['Sex'].replace({
    'Male':0,
    'Female':1
})

In [15]:
data['Sex'].value_counts()

Sex
1    160196
0    148658
Name: count, dtype: int64

In [16]:
data['Checkup'].value_counts()

Checkup
Within the past year       239371
Within the past 2 years     37213
Within the past 5 years     17442
5 or more years ago         13421
Never                        1407
Name: count, dtype: int64

In [17]:
data['Checkup'] = data['Checkup'].replace({
    'Never':0,
    'Within the past year':1,
    'Within the past 2 years':2,
    'Within the past 5 years':3,
    '5 or more years ago':4
})

data['Checkup'].value_counts()

Checkup
1    239371
2     37213
3     17442
4     13421
0      1407
Name: count, dtype: int64

In [18]:
data['Age_Category'].value_counts()

Age_Category
65-69    33434
60-64    32418
70-74    31103
55-59    28054
50-54    25097
80+      22271
40-44    21595
45-49    20968
75-79    20705
35-39    20606
18-24    18681
30-34    18428
25-29    15494
Name: count, dtype: int64

In [19]:
age_category_mapping = {
    '18-24': 0,
    '25-29': 1,
    '30-34': 2,
    '35-39': 3,
    '40-44': 4,
    '45-49': 5,
    '50-54': 6,
    '55-59': 7,
    '60-64': 8,
    '65-69': 9,
    '70-74': 10,
    '75-79': 11,
    '80+': 12
}
data['Age_Category'] = data['Age_Category'].map(age_category_mapping)    

In [20]:
data.head()

General_Health  Checkup  Exercise  Heart_Disease  Skin_Cancer  \
0               1        2         0              0            0   
1               5        1         0              1            0   
2               5        1         1              0            0   
3               1        1         1              1            0   
4               4        1         0              0            0   

   Other_Cancer  Depression Diabetes  Arthritis  Sex  Age_Category  \
0             0           0       No          1    1            10   
1             0           0      Yes          0    1            10   
2             0           0      Yes          0    1             8   
3             0           0      Yes          0    0            11   
4             0           0       No          0    0            12   

   Height_(cm)  Weight_(kg)    BMI  Smoking_History  Alcohol_Consumption  \
0        150.0        32.66  14.54                1                  0.0   
1        165.0        77.11  28.29                0                  0.0   
2        163.0        88.45  33.47                0                  4.0   
3        180.0        93.44  28.73                0                  0.0   
4        191.0        88.45  24.37                1                  0.0   

   Fruit_Consumption  Green_Vegetables_Consumption  FriedPotato_Consumption  
0               30.0                          16.0                     12.0  
1               30.0                           0.0                      4.0  
2               12.0                           3.0                     16.0  
3               30.0                          30.0                      8.0  
4                8.0                           4.0                      0.0

In [21]:
data['Age_Category'].value_counts()

Age_Category
9     33434
8     32418
10    31103
7     28054
6     25097
12    22271
4     21595
5     20968
11    20705
3     20606
0     18681
2     18428
1     15494
Name: count, dtype: int64

In [22]:
data['Age_Category'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 308854 entries, 0 to 308853
Series name: Age_Category
Non-Null Count   Dtype
--------------   -----
308854 non-null  int64
dtypes: int64(1)
memory usage: 2.4 MB


In [23]:
data.head(30)

General_Health  Checkup  Exercise  Heart_Disease  Skin_Cancer  \
0                1        2         0              0            0   
1                5        1         0              1            0   
2                5        1         1              0            0   
3                1        1         1              1            0   
4                4        1         0              0            0   
5                4        1         0              0            0   
6                2        1         1              1            0   
7                4        1         1              0            0   
8                2        1         0              0            0   
9                2        1         0              0            0   
10               2        1         1              1            0   
11               2        1         0              1            1   
12               5        1         0              0            0   
13               2        1         0              0            1   
14               3        2         1              0            0   
15               2        1         0              0            0   
16               4        1         0              0            0   
17               5        1         1              0            0   
18               2        1         1              0            0   
19               4        1         0              0            1   
20               5        2         1              0            0   
21               2        1         0              0            0   
22               5        4         1              0            0   
23               4        2         0              0            0   
24               4        1         0              0            1   
25               4        1         1              0            0   
26               2        1         0              0            0   
27               5        1         1              0            0   
28               3        1         1              0            0   
29               2        1         0              0            0   

    Other_Cancer  Depression                                 Diabetes  \
0              0           0                                       No   
1              0           0                                      Yes   
2              0           0                                      Yes   
3              0           0                                      Yes   
4              0           0                                       No   
5              0           1                                       No   
6              0           0                                       No   
7              0           0                                       No   
8              0           1                                       No   
9              0           0                                      Yes   
10             0           0                                       No   
11             0           0                                      Yes   
12             0           1                                       No   
13             0           0                                       No   
14             0           0                                       No   
15             0           0                                      Yes   
16             0           0                                       No   
17             0           0                                       No   
18             0           0                                      Yes   
19             1           0                                      Yes   
20             0           1                                       No   
21             1           0                                      Yes   
22             0           0                                       No   
23             0           0                                      Yes   
24             1           0           

In [24]:
# Columns for scaling
scale_cols = ["Height_(cm)", "Weight_(kg)", "BMI", "Alcohol_Consumption", 
              "Fruit_Consumption", "Green_Vegetables_Consumption", "FriedPotato_Consumption"]

# Perform scaling
scaler = StandardScaler()
data[scale_cols] = scaler.fit_transform(data[scale_cols])

data.head()

General_Health  Checkup  Exercise  Heart_Disease  Skin_Cancer  \
0               1        2         0              0            0   
1               5        1         0              1            0   
2               5        1         1              0            0   
3               1        1         1              1            0   
4               4        1         0              0            0   

   Other_Cancer  Depression Diabetes  Arthritis  Sex  Age_Category  \
0             0           0       No          1    1            10   
1             0           0      Yes          0    1            10   
2             0           0      Yes          0    1             8   
3             0           0      Yes          0    0            11   
4             0           0       No          0    0            12   

   Height_(cm)  Weight_(kg)       BMI  Smoking_History  Alcohol_Consumption  \
0    -1.934250    -2.386180 -2.159696                1            -0.621527   
1    -0.526857    -0.303547 -0.051548                0            -0.621527   
2    -0.714510     0.227770  0.742649                0            -0.133707   
3     0.880535     0.461569  0.015913                0            -0.621527   
4     1.912623     0.227770 -0.652562                1            -0.621527   

   Fruit_Consumption  Green_Vegetables_Consumption  FriedPotato_Consumption  
0           0.006625                      0.059597                 0.664502  
1           0.006625                     -1.012342                -0.267579  
2          -0.716973                     -0.811354                 1.130543  
3           0.006625                      0.997544                 0.198462  
4          -0.877772                     -0.744358                -0.733620

In [25]:
# Mapping for Diabetes
diabetes_mapping = {
    'No': 0, 
    'No, pre-diabetes or borderline diabetes': 0, 
    'Yes, but female told only during pregnancy': 1,
    'Yes': 1
}
data['Diabetes'] = data['Diabetes'].map(diabetes_mapping)

In [26]:
data.head()

General_Health  Checkup  Exercise  Heart_Disease  Skin_Cancer  \
0               1        2         0              0            0   
1               5        1         0              1            0   
2               5        1         1              0            0   
3               1        1         1              1            0   
4               4        1         0              0            0   

   Other_Cancer  Depression  Diabetes  Arthritis  Sex  Age_Category  \
0             0           0         0          1    1            10   
1             0           0         1          0    1            10   
2             0           0         1          0    1             8   
3             0           0         1          0    0            11   
4             0           0         0          0    0            12   

   Height_(cm)  Weight_(kg)       BMI  Smoking_History  Alcohol_Consumption  \
0    -1.934250    -2.386180 -2.159696                1            -0.621527   
1    -0.526857    -0.303547 -0.051548                0            -0.621527   
2    -0.714510     0.227770  0.742649                0            -0.133707   
3     0.880535     0.461569  0.015913                0            -0.621527   
4     1.912623     0.227770 -0.652562                1            -0.621527   

   Fruit_Consumption  Green_Vegetables_Consumption  FriedPotato_Consumption  
0           0.006625                      0.059597                 0.664502  
1           0.006625                     -1.012342                -0.267579  
2          -0.716973                     -0.811354                 1.130543  
3           0.006625                      0.997544                 0.198462  
4          -0.877772                     -0.744358                -0.733620

In [27]:
# Defining the features (X) and the target (y)
X = data.drop("Heart_Disease", axis=1)
y = data["Heart_Disease"]

# Performing the train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

X_train.shape, X_test.shape, y_train.shape, y_test.shape

((247083, 18), (61771, 18), (247083,), (61771,))

In [28]:
# Defining the function to apply models
def apply_model(model, X_train, y_train, X_test, y_test):
    # Fit the model
    model.fit(X_train, y_train)

    # Make predictions
    y_pred = model.predict(X_test)

    # Calculate performance metrics
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
        # Compute ROC curve and ROC area
    y_pred_proba = model.predict_proba(X_test)[:, 1]
    fpr, tpr, _ = roc_curve(y_test, y_pred_proba)
    roc_auc = roc_auc_score(y_test, y_pred_proba)

    return accuracy, precision, recall, f1, fpr, tpr, roc_auc

# Defining the models
models = [
    ("Logistic Regression", LogisticRegression(random_state=42, max_iter=500)),
    ("Decision Tree", DecisionTreeClassifier(random_state=42)),
    ("Random Forest", RandomForestClassifier(random_state=42))
    
]
# Applying the models and storing the results
results = []
roc_curves = []

for name, model in models:
    accuracy, precision, recall, f1, fpr, tpr, roc_auc = apply_model(model, X_train, y_train, X_test, y_test)
    results.append((name, accuracy, precision, recall, f1))
    roc_curves.append((name, fpr, tpr, roc_auc))

results, roc_curves

([('Logistic Regression',
   0.9196386653931456,
   0.52994555353902,
   0.05843506103662197,
   0.10526315789473684),
  ('Decision Tree',
   0.86195787667352,
   0.19304347826086957,
   0.2221332799679808,
   0.20656927514655254),
  ('Random Forest',
   0.91835974810186,
   0.4541832669322709,
   0.045627376425855515,
   0.08292416803055101)],
 [('Logistic Regression',
   array([0.00000000e+00, 1.76136964e-05, 1.76136964e-05, ...,
          9.87582344e-01, 9.87582344e-01, 1.00000000e+00]),
   array([0.00000000e+00, 0.00000000e+00, 2.00120072e-04, ...,
          9.99799880e-01, 1.00000000e+00, 1.00000000e+00]),
   0.8244519614858359),
  ('Decision Tree',
   array([0.        , 0.08172755, 0.08174517, 1.        ]),
   array([0.        , 0.22213328, 0.2223334 , 1.        ]),
   0.5702878961321909),
  ('Random Forest',
   array([0.00000000e+00, 1.76136964e-05, 5.28410892e-05, 7.04547856e-05,
          8.80684821e-05, 1.40909571e-04, 1.40909571e-04, 2.81819143e-04,
          3.69887625e-04,